version: '3'
services:
  # server:
  #   build: ./server
  #   ports:
  #     - '3002:3002'
  #   depends_on:
  #     - database
  #   env_file: .env

  database:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: invoice-test
